#!/usr/bin/with-contenv bash

if [[ -z ${PUBLIC_KEY} || -z ${END_POINT} ]]; then
  echo "Finding the best server..."
  recommendations=$(curl --retry "${RETRY:-5}" -LsS "https://api.nordvpn.com/v1/servers/recommendations?&filters\[servers_technologies\]\[identifier\]=wireguard_udp&limit=1&${QUERY}")
  if [[ -z ${PUBLIC_KEY} ]]; then
    PUBLIC_KEY=$(jq -r '.[0].technologies[] | select( .identifier == "wireguard_udp" ) | .metadata[] | select( .name == "public_key" ) | .value' <<< "${recommendations}")
  fi
  if [[ -z ${END_POINT} ]]; then
    END_POINT=$(jq -r '.[0].hostname' <<< "${recommendations}"):51820
  fi
fi

cat >/etc/wireguard/wg0.conf <<EOF
[Interface]
PrivateKey = ${PRIVATE_KEY}
ListenPort = ${LISTEN_PORT:-51820}
Address = ${ADDRESS:-10.5.0.2/32}
DNS = ${DNS:-103.86.96.100,103.86.99.100}
Table = ${TABLE:-auto}
PreUp = ${PRE_UP}
PostUp = ${POST_UP}
PreDown = ${PRE_DOWN}
PostDown = ${POST_DOWN}

[Peer]
PublicKey = ${PUBLIC_KEY}
AllowedIPs = ${ALLOWED_IPS:-0.0.0.0/0}
Endpoint = ${END_POINT}
PersistentKeepalive = ${PERSISTENT_KEEP_ALIVE:-25}
EOF

chmod 600 /etc/wireguard/wg0.conf

echo "Connecting to ${END_POINT}..."
nslookup $(echo "${END_POINT}" | cut -d":" -f1) | grep "^Name:" -A1 || true
wg-quick up wg0
wg show wg0

sleep "${RECONNECT_TIME:-infinity}"
